name: "Quality Checks"

on:
  pull_request:
    types: [ "opened", "reopened", "synchronize" ]
  workflow_dispatch: {}

env:
  MAVEN_SETTINGS: ${{ secrets.MAVEN_SETTINGS }}
  MAVEN_SETTINGS_SECURITY: ${{ secrets.MAVEN_SETTINGS_SECURITY }}

jobs:
  run-tests:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
      - name: "Setup"
        uses: dedalus-cis4u/with-standard-setup@v2.0.15
        with:
          git-checkout: 'all'
          maven: true
          java: 21

      - name: "Run tests"
        run: mvn -ntp clean verify

      - name: "Upload coverage report"
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: jacoco-report-aggregate/target/site/jacoco-aggregate/jacoco.xml
          if-no-files-found: error

  run-sonar:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: "Setup"
        uses: dedalus-cis4u/with-standard-setup@v2.0.15
        with:
          maven: true
          java: 21

      - name: "Download coverage report"
        uses: actions/download-artifact@v4
        with:
          name: coverage
          path: coverage

      - name: "Run SonarQube Analysis (manually triggered)"
        if: github.event_name == 'workflow_dispatch'
        run: |
          $SONAR_CMD_BASE

      - name: "Run SonarQube Analysis (pull request)"
        if: github.event_name == 'pull_request'
        run: |
          $SONAR_CMD_BASE \
            -Dsonar.pullrequest.provider=github \
            -Dsonar.pullrequest.key=$CI_PR_NUMBER \
            -Dsonar.pullrequest.branch=$CI_GITHUB_HEAD_REF \
            -Dsonar.pullrequest.base=$CI_GITHUB_BASE_REF \
            -Dsonar.pullrequest.github.repository=$CI_GITHUB_REPOSITORY \
            -Dsonar.scm.provider=git